baseURL = "https://hellupline.com.br/"
languageCode = "en-us"
title = "HellUpline utils"
theme = "book"
enableGitInfo = true

pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
BookEnableJS = true
