---
apiVersion: v1
kind: Pod
metadata:
    name: my-pvc-pod
spec:
    containers:
      - name: my-pvc-pod-nginx
        image: nginx
        volumeMounts:
          - {name: my-pvc-data, mountPath: "/usr/share/nginx/html"}
        ports:
          - {name: http, containerPort: 80, hostPort: 80}
    volumes:
      - {name: my-pvc-data, persistentVolumeClaim: {claimName: my-pvc}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-pvc
spec:
    resources: requests: {storage: 3Gi}
    accessModes: [ReadWriteOnce]
