---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url:
sections:
- type: directory
  path: content/docs/kubernetes
  label: Kubernetes
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: content/docs/aws
  label: AWS
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: content/docs/scripts
  label: Scripts
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: content/docs/terminal
  label: Terminal
  create: all
  match: "**/*"
  templates:
  - default
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview:
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
