---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels: {app: my-app}
    name: my-app
    namespace: my-namespace
spec:
    strategy: {rollingUpdate: {maxUnavailable: 0, maxSurge: 1}, type: RollingUpdate}
    replicas: 3
    minReadySeconds: 30
    selector: {matchLabels: {app: my-app}}
    template:
        metadata: {labels: {app: my-app}}
        spec:
            # prefer one per node
            affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - labelSelector:
                        matchExpressions:
                          - {key: app, operator: In, values: [my-app]}
                      topologyKey: kubernetes.io/hostname

            restartPolicy: Always
            containers:
              - name: my-app
                imagePullPolicy: Always
                image: nginx

                # pod environment
                volumeMounts:
                  - {name: secret-files, mountPath: "/my-app/secret/", readOnly: true}
                  - {name: config-files, mountPath: "/my-app/config/", readOnly: true}
                  - {name: volume-files, mountPath: "/my-app/volume/", readOnly: false}
                  - {name: cached-files, mountPath: "/my-app/cached/", readOnly: false}
                ports:
                  - {name: http, containerPort: 80, hostPort: 80}
                resources:
                    requests: {memory: "32Mi", cpu: "50m"}
                    limits: {memory: "256Mi", cpu: "200m"}
                envFrom:
                  - secretRef: {name: my-app-secret}
                  - configMapRef: {name: my-app-config}
                env:
                  - {name: SECRET_ENV, valueFrom: {secretKeyRef: {name: my-app-secret, key: SECRET_ENV}}}
                  - {name: CONFIG_ENV, valueFrom: {configMapKeyRef: {name: my-app-config, key: CONFIG_ENV}}}
                  - {name: ENV_NAME, value: "ENV_VALUE"}

                # pod health
                readinessProbe:
                    httpGet:  # do a http request
                        httpHeaders: [{name: Host, value: "my-app.my-domain.com"}]
                        path: "/my-path/"
                        port: http
                        scheme: HTTP
                    tcpSocket:  # do a tcp socket probe
                        port: http
                    exec:  # run a command
                        command: ["cat", "/tmp/healthy"]
                    # probe settings
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 4
                    successThreshold: 1
                    failureThreshold: 5

                livenessProbe:
                    httpGet:  # do a http request
                        httpHeaders: [{name: Host, value: "my-app.my-domain.com"}]
                        path: "/my-path/"
                        port: http
                        scheme: HTTP
                    tcpSocket:  # do a tcp socket probe
                        port: http
                    exec:  # run a command
                        command: [cat, "/tmp/healthy"]
                    # probe settings
                    initialDelaySeconds: 5
                    periodSeconds: 5
                    timeoutSeconds: 4
                    successThreshold: 1
                    failureThreshold: 5

            volumes:
              - name: secret-files
                secret:
                    secretName: my-app-secret
                    items:
                      - {key: SECRET_FILE, path: secret.json}
              - name: config-files
                configMap:
                    name: my-app-config
                    items:
                      - {key: CONFIG_FILE, path: config.json}
              - {name: volume-files, persistentVolumeClaim: {claimName: my-pvc}}
              - {name: cached-files, emptyDir: {}}
