---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: weight
  type: number
  label: Weight
  description: ''
  default: 99
  config:
    min: 0
    max: 99
    step: 1
    required: true
pages:
- content/docs/kubernetes/commands.md
- content/docs/kubernetes/commands.md
- content/docs/applications/postgresql.md
- content/docs/kubernetes/config-example/pod.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/kubernetes/config-example/service.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/kubernetes/config-example/statefulset.md
- content/docs/kubernetes/config-example/namespace.md
- content/docs/kubernetes/config-example/service.md
- content/docs/kubernetes/config-example/volumes.md
- content/docs/kubernetes/config-example/cronjob.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/kubernetes/config-example/job.md
- content/docs/kubernetes/config-example/rbac.md
- content/stuffs.md
- content/docs/terminal/utils.md
- content/docs/terminal/ssl.md
- content/docs/terminal/random.md
- content/docs/terminal/osx.md
- content/docs/terminal/linux.md
- content/docs/terminal/curl.md
- content/docs/terminal/_index.md
- content/docs/scripts/website-down-alarm.md
- content/docs/aws/amazon-linux-ami-per-region.md
- content/docs/aws/_index.md
- content/docs/applications/nginx.md
- content/docs/applications/mysql.md
- content/docs/applications/_index.md
- content/_index.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/scripts/_index.md
- content/gallery.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/kubernetes/_index.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/archlinux/install.md
- content/docs/archlinux/_index.md
- content/docs/kubernetes/_index.md
