---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: weight
  type: number
  label: Weight
  description: ''
  default: 99
  config:
    min: 0
    max: 99
    step: 1
    required: true
pages:
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/kubernetes/config-example/service.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/tips/_index.md
- content/docs/scripts/_index.md
- content/gallery.md
- content/docs/kubernetes/config-example/statefulset.md
- content/docs/kubernetes/config-example/cronjob.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/kubernetes/config-example/rbac.md
- content/docs/kubernetes/config-example/volumes.md
- content/docs/kubernetes/config-example/namespace.md
- content/docs/kubernetes/config-example/service.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/kubernetes/config-example/job.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/tips/_index.md
- content/docs/kubernetes/commands.md
- content/docs/kubernetes/commands.md
- content/docs/kubernetes/_index.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/archlinux/install.md
- content/docs/archlinux/_index.md
- content/docs/kubernetes/_index.md
