---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: weight
  type: number
  label: Weight
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
pages:
- content/docs/shell-script/monitoring/website.md
- content/docs/shell-script/monitoring/_index.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/service.md
- content/docs/archlinux/install.md
- content/docs/archlinux/_index.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/kubernetes/_index.md
- content/docs/kubernetes/commands.md
