---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- name: weight
  type: number
  label: Weight
  description: ''
  default: 99
  config:
    min: 0
    max: 99
    step: 1
    required: true
pages:
- content/docs/shell-scripts/website-alarm.md
- content/docs/shell-scripts/_index.md
- content/docs/tips/terminal/_index.md
- content/docs/tips/terminal/osx.md
- content/docs/tips/_index.md
- content/docs/tips/applications/_index.md
- content/docs/tips/applications/nginx.md
- content/docs/tips/applications/postgresql.md
- content/docs/tips/terminal/ssl.md
- content/docs/tips/terminal/utils.md
- content/docs/tips/terminal/curl.md
- content/docs/kubernetes/_index.md
- content/docs/kubernetes/config-example/service.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/kubernetes/commands.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/kubernetes/config-example/hpa.md
- content/docs/tips/terminal/curl.md
- content/docs/kubernetes/config-example/ingress.md
- content/docs/tips/terminal/utils.md
- content/docs/tips/terminal/ssl.md
- content/docs/tips/applications/postgresql.md
- content/docs/kubernetes/config-example/deployment.md
- content/docs/tips/applications/nginx.md
- content/docs/tips/applications/_index.md
- content/docs/tips/_index.md
- content/docs/tips/terminal/osx.md
- content/docs/tips/terminal/_index.md
- content/docs/kubernetes/config-example/_index.md
- content/docs/kubernetes/commands.md
- content/docs/kubernetes/config-example/secret.md
- content/docs/kubernetes/config-example/configmap.md
- content/docs/kubernetes/config-example/service.md
- content/docs/archlinux/install.md
- content/docs/archlinux/_index.md
- content/docs/kubernetes/_index.md
